Updated steps to combined release notes and checksum

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -78,106 +78,6 @@ jobs:
             --certificate-identity-regexp=https://github.com/${{ github.repository_owner }} \
             --certificate-oidc-issuer=https://token.actions.githubusercontent.com
 
-      - name: Checksum
-        run: |
-          pushd release
-          shasum -a 256 ./release.yml ./package.yml ./package-metadata.yml | tee ../tmp/checksums.txt
-          popd
-        
-      - name: Sign checksums.txt
-        run: |
-            cosign sign-blob --yes ./tmp/checksums.txt --output-certificate release/checksums.txt.pem  --output-signature release/checksums.txt.sig
-      - name: Verify checksums signature
-        run: |
-          cosign verify-blob \
-          --cert release/checksums.txt.pem \
-          --signature release/checksums.txt.sig \
-          --certificate-identity-regexp=https://github.com/${{ github.repository_owner }} \
-          --certificate-oidc-issuer=https://token.actions.githubusercontent.com ./tmp/checksums.txt
-
-      - name: Create release draft and upload release yaml
-        uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
-        with:
-          name: ${{ github.ref_name }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          body_path: ./tmp/checksums.txt
-          files: |
-            ./release/*
-          draft: true
-      - name: Get uploaded release YAML checksum
-        uses: actions/github-script@v6
-        id: get-checksums-from-draft-release
-        if: startsWith(github.ref, 'refs/tags/')
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          result-encoding: string
-          script: |
-            var crypto = require('crypto');
-            const { owner, repo } = context.repo;
-            // https://docs.github.com/en/rest/reference/repos#list-releases
-            // https://octokit.github.io/rest.js/v18#repos-list-releases
-            var releases = await github.rest.repos.listReleases({
-              owner: owner,
-              repo: repo
-            });
-            var crypto = require('crypto')
-            var fs = require('fs')
-            const url = require('url');
-            const https = require('https');
-            checksums = {}
-            var releaseMatched = false;
-            var assetsFound = false;
-            for (const r of releases["data"]) {
-              if (r.draft && `refs/tags/${r.tag_name}` == "${{ github.ref }}") {
-                releaseMatched = true;
-                for (const asset of r.assets) {
-                  assetsFound = true;
-                  var release_asset = await github.rest.repos.getReleaseAsset({ headers: {accept: `application/octet-stream`}, accept: `application/octet-stream`, owner: owner, repo: repo, asset_id: asset.id });
-                  const hash = crypto.createHash('sha256');
-                  let http_promise = new Promise((resolve, reject) => {
-                    https.get(release_asset.url, (stream) => {
-                      stream.on('data', function (data) {
-                        hash.update(data);
-                      });
-                      stream.on('end', function () {
-                        checksums[asset.name]= hash.digest('hex');
-                        resolve(`${asset.name}`);
-                      });
-                    });
-                  });
-                  await http_promise;
-                  http_promise.then(
-                    (result) => {
-                        console.log(checksums);
-                    },
-                    (error) => {
-                        console.log("Encountered an Error for " + asset.name + " asset: " + error); // Log an error
-                    });
-                }
-              }
-            }
-            if (!releaseMatched) {
-              console.log("No release matched")
-            }
-            if (!assetsFound) {
-              console.log("No assets found for " + "${{ github.ref }}" + " release")
-            }
-            return `${checksums['release.yml']}  ./release.yml
-            ${checksums['package.yml']}  ./package.yml
-            ${checksums['package-metadata.yml']}  ./package-metadata.yml`
-      
-      - name: Verify uploaded artifacts
-        if: startsWith(github.ref, 'refs/tags/')
-        env:
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-        run: |
-          set -e -x
-          cat ./tmp/checksums.txt
-          diff ./tmp/checksums.txt <(cat <<EOF
-          ${{steps.get-checksums-from-draft-release.outputs.result}}
-          EOF
-          )
-      
       - name: Updating release notes
         run: |
           RELEASE_TAG=$(git describe --tags --abbrev=0)
@@ -255,10 +155,108 @@ jobs:
           </summary>
           </details>
           "
-          RELEASE_NOTES_UPLOADED=$(gh release view $RELEASE_TAG --json body | jq -r '.body')
-          RELEASE_NOTES+=$RELEASE_NOTES_UPLOADED
-          echo "$RELEASE_NOTES" > release_notes.txt
-          gh release edit $RELEASE_TAG --notes-file release_notes.txt
+          echo "$RELEASE_NOTES" > ./tmp/release_notes.txt
+
+      - name: Create checksum and add it to release notes
+        run: |
+          pushd release
+          shasum -a 256 ./release.yml ./package.yml ./package-metadata.yml | tee ../tmp/checksums.txt
+          popd
+          cat ./tmp/checksums.txt | tee -a ./tmp/release_notes.txt
+        
+      - name: Sign checksums.txt
+        run: |
+            cosign sign-blob --yes ./tmp/checksums.txt --output-certificate release/checksums.txt.pem  --output-signature release/checksums.txt.sig
+      - name: Verify checksums signature
+        run: |
+          cosign verify-blob \
+          --cert release/checksums.txt.pem \
+          --signature release/checksums.txt.sig \
+          --certificate-identity-regexp=https://github.com/${{ github.repository_owner }} \
+          --certificate-oidc-issuer=https://token.actions.githubusercontent.com ./tmp/checksums.txt
+
+      - name: Create release draft and upload release yaml
+        uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
+        with:
+          name: ${{ github.ref_name }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          body_path: ./tmp/release_notes.txt
+          files: |
+            ./release/*
+          draft: true
+      - name: Get uploaded release YAML checksum
+        uses: actions/github-script@v6
+        id: get-checksums-from-draft-release
+        if: startsWith(github.ref, 'refs/tags/')
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          result-encoding: string
+          script: |
+            var crypto = require('crypto');
+            const { owner, repo } = context.repo;
+            // https://docs.github.com/en/rest/reference/repos#list-releases
+            // https://octokit.github.io/rest.js/v18#repos-list-releases
+            var releases = await github.rest.repos.listReleases({
+              owner: owner,
+              repo: repo
+            });
+            var crypto = require('crypto')
+            var fs = require('fs')
+            const url = require('url');
+            const https = require('https');
+            checksums = {}
+            var releaseMatched = false;
+            var assetsFound = false;
+            for (const r of releases["data"]) {
+              if (r.draft && `refs/tags/${r.tag_name}` == "${{ github.ref }}") {
+                releaseMatched = true;
+                for (const asset of r.assets) {
+                  assetsFound = true;
+                  var release_asset = await github.rest.repos.getReleaseAsset({ headers: {accept: `application/octet-stream`}, accept: `application/octet-stream`, owner: owner, repo: repo, asset_id: asset.id });
+                  const hash = crypto.createHash('sha256');
+                  let http_promise = new Promise((resolve, reject) => {
+                    https.get(release_asset.url, (stream) => {
+                      stream.on('data', function (data) {
+                        hash.update(data);
+                      });
+                      stream.on('end', function () {
+                        checksums[asset.name]= hash.digest('hex');
+                        resolve(`${asset.name}`);
+                      });
+                    });
+                  });
+                  await http_promise;
+                  http_promise.then(
+                    (result) => {
+                        console.log(checksums);
+                    },
+                    (error) => {
+                        console.log("Encountered an Error for " + asset.name + " asset: " + error); // Log an error
+                    });
+                }
+              }
+            }
+            if (!releaseMatched) {
+              console.log("No release matched")
+            }
+            if (!assetsFound) {
+              console.log("No assets found for " + "${{ github.ref }}" + " release")
+            }
+            return `${checksums['release.yml']}  ./release.yml
+            ${checksums['package.yml']}  ./package.yml
+            ${checksums['package-metadata.yml']}  ./package-metadata.yml`
+      
+      - name: Verify uploaded artifacts
+        if: startsWith(github.ref, 'refs/tags/')
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: |
+          set -e -x
+          cat ./tmp/checksums.txt
+          diff ./tmp/checksums.txt <(cat <<EOF
+          ${{steps.get-checksums-from-draft-release.outputs.result}}
+          EOF
+          )
 
       - name: Run PackageCR Validation Tests
         run: |
